Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu.server.org"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 4096
    vm.cpus = 4
  end

  config.vm.provision :shell, name: "install-prerequisites", path: "third-party-install.sh"
  config.vm.provision :shell, name: "install-cmake", path: "cmake-install.sh"
  config.vm.provision :shell, privileged: false, name: "compile-or-tools", path: "or-tools-compile.sh"
  config.vm.provision :shell, privileged: false, name: "package-or-tools", path: "or-tools-package.sh"
end
