$script = <<SCRIPT
if [ ! -d cmake-3.8.2 ]; then
    wget https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz --quiet -Ocmake-3.8.2.tar.gz \
    && tar -xzf cmake-3.8.2.tar.gz \
    && rm cmake-3.8.2.tar.gz \
    && cd cmake-3.8.2 \
    && ./bootstrap --no-qt-gui --system-curl && make package
    cd --
fi
SCRIPT

# && sudo make install

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu.server.org"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 4096
    vm.cpus = 4
  end
  config.vm.provision "shell", inline: $script
end
