Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.hostname = "debian.server.org"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 4096
    vm.cpus = 4
  end
  config.vm.synced_folder "../shared", "/shared", :mount_options => ["ro"]

  config.vm.provision :shell, name: "install-prerequisites", path: "../shared/third-party-install.sh"
  config.vm.provision :shell, name: "install-cmake", path: "../shared/cmake-install.sh"
  config.vm.provision :shell, privileged: false, name: "compile-or-tools", path: "../shared/or-tools-compile.sh"
  config.vm.provision :shell, privileged: false, name: "package-or-tools", path: "../shared/or-tools-package.sh"
end
