$script = <<SCRIPT
sudo apt-get upgrade
sudo apt-get install --assume-yes cmake g++ autoconf build-essential libtool git
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"
  config.vm.hostname = "debian.server.org"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 4096
    vm.cpus = 4
  end
  config.vm.synced_folder "../../shared", "/shared", :mount_options => ["ro"]

  config.vm.provision :shell, name: "install-prerequisites", inline: $script
  config.vm.provision :shell, name: "package-rest", path: "../../shared/package_rest.sh"
end
